### ISSUE TITLE
[ADD]: "Zonemaster"

### ISSUE THREAD

**Issue by marc-vanderwal** [CENTRprojects/awesome-dns#2]
### Software name

Zonemaster

### Software webpage

https://zonemaster.net

### Software description

A software package that validates the quality of a DNS delegation.

### Editing organization

Afnic and The Swedish Internet Foundation

### Software license

BSD (3-clause)

### Category name

Testing tools

### New category

- [X] Yes, it's a new category
- [ ] No, it's an existing category

### Motivation

Testing tools are a useful category in the “Awesome DNS” list. Such tools are helpful not only for conducting diagnoses of DNS configurations, but also as a learning resource.

Zonemaster is a prime example of such a testing tool. It is the result of a long-stading collaboration between Afnic and The Swedish Internet Foundation. It is estimated that over 500,000 tests are completed each month on zonemaster.iis.se, zonemaster.net and zonemaster.fr combined.

### Request checklist

- [X] I have checked for other similar issues and pull requests.
- [X] I have replaced "Software name" by the actual name of the software in the title

- [X] I have filled all mandatory fields

**Comment by mylespat** [comment]
Thank you!

From: Marc van der Wal ***@***.***>
Sent: Thursday, May 4, 2023 4:57 PM
To: CENTRprojects/awesome-dns ***@***.***>
Cc: Patrick Myles ***@***.***>; Assign ***@***.***>
Subject: [CENTRprojects/awesome-dns] [ADD]: "Zonemaster" (Issue #2)

Software name

Zonemaster

Software webpage

https://zonemaster.net

Software description

A software package that validates the quality of a DNS delegation.

Editing organization

Afnic and The Swedish Internet Foundation

Software license

BSD (3-clause)

Category name

Testing tools

New category

  *   [X] Yes, it's a new category
  *   [ ] No, it's an existing category

Motivation

Testing tools are a useful category in the “Awesome DNS” list. Such tools are helpful not only for conducting diagnoses of DNS configurations, but also as a learning resource.

Zonemaster is a prime example of such a testing tool. It is the result of a long-stading collaboration between Afnic and The Swedish Internet Foundation. It is estimated that over 500,000 tests are completed each month on zonemaster.iis.se, zonemaster.net and zonemaster.fr combined.

Request checklist

  *   [X] I have checked for other similar issues and pull requests.
  *   [X] I have replaced "Software name" by the actual name of the software in the title
  *   [X] I have filled all mandatory fields
