### ISSUE TITLE
[ADD]: "EduDig"

### ISSUE THREAD

**Issue by romu42** [CENTRprojects/awesome-dns#3]
### Software name

EduDig

### Software webpage

https://edudig.se/

### Software description

A web "dig" tool that is built to help understand DNS and dig

### Editing organization

The Swedish Internet Foundation

### Software license

MIT

### Category name

DNS Education

### New category

- [X] Yes, it's a new category
- [ ] No, it's an existing category

### Motivation

This is a project that we are working on at the Swedish Internet Foundation, it is not "Production Ready", but we are making progress on it and would like to keep the traction. Input from the community for direction, code, and opinions is welcome.

The goal is to build a web "dig" tool that helps with DNS education and presentations. 

### Request checklist

- [X] I have checked for other similar issues and pull requests.
- [X] I have replaced "Software name" by the actual name of the software in the title

- [X] I have filled all mandatory fields

**Comment by thymen** [comment]
Hi @romu42,

Thanks for suggesting EduDig and apologies for the late response. I just added it to the list.

Best,
Thymen
